=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'

# Unit tests for Authentik::Api::RequestsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RequestsApi' do
  before do
    # run before each test
    @api_instance = Authentik::Api::RequestsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequestsApi' do
    it 'should create an instance of RequestsApi' do
      expect(@api_instance).to be_instance_of(Authentik::Api::RequestsApi)
    end
  end

  # unit tests for requests_grant_requests_create
  # @param grant_request_create_request 
  # @param [Hash] opts the optional parameters
  # @return [Link]
  describe 'requests_grant_requests_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_destroy
  # @param uuid A UUID string identifying this Grant Request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'requests_grant_requests_destroy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_fulfill_partial_update
  # @param uuid A UUID string identifying this Grant Request.
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedGrantRequestFulfillRequest] :patched_grant_request_fulfill_request 
  # @return [nil]
  describe 'requests_grant_requests_fulfill_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :created_by 
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :search A search term.
  # @option opts [RequestStatus] :status 
  # @return [PaginatedGrantRequestList]
  describe 'requests_grant_requests_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_pending_review_list
  # List pending grant requests the current user is eligible to review.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :created_by 
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :search A search term.
  # @option opts [RequestStatus] :status 
  # @return [PaginatedGrantRequestList]
  describe 'requests_grant_requests_pending_review_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_retrieve
  # @param uuid A UUID string identifying this Grant Request.
  # @param [Hash] opts the optional parameters
  # @return [GrantRequest]
  describe 'requests_grant_requests_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_grant_requests_revoke_destroy
  # Immediately end an active grant. Available to the same reviewers who could approve it in the first place.
  # @param uuid A UUID string identifying this Grant Request.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'requests_grant_requests_revoke_destroy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_create
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param request_rule_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleBinding]
  describe 'requests_rule_bindings_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_destroy
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Binding.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'requests_rule_bindings_destroy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_list
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :rule 
  # @option opts [String] :search A search term.
  # @option opts [String] :target 
  # @return [PaginatedRequestRuleBindingList]
  describe 'requests_rule_bindings_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_partial_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Binding.
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedRequestRuleBindingRequest] :patched_request_rule_binding_request 
  # @return [RequestRuleBinding]
  describe 'requests_rule_bindings_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_retrieve
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Binding.
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleBinding]
  describe 'requests_rule_bindings_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Binding.
  # @param request_rule_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleBinding]
  describe 'requests_rule_bindings_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_bindings_used_by_list
  # Get a list of all objects that use this object
  # @param uuid A UUID string identifying this Request Rule Binding.
  # @param [Hash] opts the optional parameters
  # @return [Array<UsedBy>]
  describe 'requests_rule_bindings_used_by_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_create
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param request_rule_child_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleChildBinding]
  describe 'requests_rule_child_bindings_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_destroy
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Child Binding.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'requests_rule_child_bindings_destroy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_list
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param [Hash] opts the optional parameters
  # @option opts [String] :binding 
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :search A search term.
  # @option opts [String] :target 
  # @return [PaginatedRequestRuleChildBindingList]
  describe 'requests_rule_child_bindings_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_partial_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Child Binding.
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedRequestRuleChildBindingRequest] :patched_request_rule_child_binding_request 
  # @return [RequestRuleChildBinding]
  describe 'requests_rule_child_bindings_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_retrieve
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Child Binding.
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleChildBinding]
  describe 'requests_rule_child_bindings_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule Child Binding.
  # @param request_rule_child_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRuleChildBinding]
  describe 'requests_rule_child_bindings_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rule_child_bindings_used_by_list
  # Get a list of all objects that use this object
  # @param uuid A UUID string identifying this Request Rule Child Binding.
  # @param [Hash] opts the optional parameters
  # @return [Array<UsedBy>]
  describe 'requests_rule_child_bindings_used_by_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_create
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param request_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRule]
  describe 'requests_rules_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_destroy
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'requests_rules_destroy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_list
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [String] :pbm_uuid 
  # @option opts [String] :request_flow__slug 
  # @option opts [String] :search A search term.
  # @return [PaginatedRequestRuleList]
  describe 'requests_rules_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_partial_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule.
  # @param [Hash] opts the optional parameters
  # @option opts [PatchedRequestRuleRequest] :patched_request_rule_request 
  # @return [RequestRule]
  describe 'requests_rules_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_retrieve
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule.
  # @param [Hash] opts the optional parameters
  # @return [RequestRule]
  describe 'requests_rules_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_update
  # Mixin to add a used_by endpoint to return a list of all objects using this object
  # @param uuid A UUID string identifying this Request Rule.
  # @param request_rule_request 
  # @param [Hash] opts the optional parameters
  # @return [RequestRule]
  describe 'requests_rules_update test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for requests_rules_used_by_list
  # Get a list of all objects that use this object
  # @param uuid A UUID string identifying this Request Rule.
  # @param [Hash] opts the optional parameters
  # @return [Array<UsedBy>]
  describe 'requests_rules_used_by_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
