=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'

# Unit tests for Authentik::Api::RootApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RootApi' do
  before do
    # run before each test
    @api_instance = Authentik::Api::RootApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RootApi' do
    it 'should create an instance of RootApi' do
      expect(@api_instance).to be_instance_of(Authentik::Api::RootApi)
    end
  end

  # unit tests for root_config_retrieve
  # Retrieve public configuration options
  # @param [Hash] opts the optional parameters
  # @return [Config]
  describe 'root_config_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
