=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'

# Unit tests for Authentik::Api::SsfApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SsfApi' do
  before do
    # run before each test
    @api_instance = Authentik::Api::SsfApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SsfApi' do
    it 'should create an instance of SsfApi' do
      expect(@api_instance).to be_instance_of(Authentik::Api::SsfApi)
    end
  end

  # unit tests for ssf_streams_list
  # SSFStream Viewset
  # @param [Hash] opts the optional parameters
  # @option opts [String] :delivery_method 
  # @option opts [String] :endpoint_url 
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :page A page number within the paginated result set.
  # @option opts [Integer] :page_size Number of results to return per page.
  # @option opts [Integer] :provider 
  # @option opts [String] :search A search term.
  # @return [PaginatedSSFStreamList]
  describe 'ssf_streams_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ssf_streams_retrieve
  # SSFStream Viewset
  # @param uuid A UUID string identifying this SSF Stream.
  # @param [Hash] opts the optional parameters
  # @return [SSFStream]
  describe 'ssf_streams_retrieve test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
