=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Authentik::Api::Hardware
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Authentik::Api::Hardware do
  #let(:instance) { Authentik::Api::Hardware.new }

  describe 'test an instance of Hardware' do
    it 'should create an instance of Hardware' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Authentik::Api::Hardware)
    end
  end

  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "manufacturer"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "serial"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cpu_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cpu_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "memory_bytes"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
