=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Authentik::Api::IframeLogoutChallengeResponseRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Authentik::Api::IframeLogoutChallengeResponseRequest do
  #let(:instance) { Authentik::Api::IframeLogoutChallengeResponseRequest.new }

  describe 'test an instance of IframeLogoutChallengeResponseRequest' do
    it 'should create an instance of IframeLogoutChallengeResponseRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Authentik::Api::IframeLogoutChallengeResponseRequest)
    end
  end

  describe 'test attribute "component"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
