=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Authentik::Api::MicrosoftEntraProviderUserRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Authentik::Api::MicrosoftEntraProviderUserRequest do
  #let(:instance) { Authentik::Api::MicrosoftEntraProviderUserRequest.new }

  describe 'test an instance of MicrosoftEntraProviderUserRequest' do
    it 'should create an instance of MicrosoftEntraProviderUserRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Authentik::Api::MicrosoftEntraProviderUserRequest)
    end
  end

  describe 'test attribute "microsoft_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "provider"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
