=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Authentik::Api::OffboardingStatusEnum
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Authentik::Api::OffboardingStatusEnum do
  #let(:instance) { Authentik::Api::OffboardingStatusEnum.new }

  describe 'test an instance of OffboardingStatusEnum' do
    it 'should create an instance of OffboardingStatusEnum' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Authentik::Api::OffboardingStatusEnum)
    end
  end

end
