=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Authentik::Api::ReputationPolicyRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Authentik::Api::ReputationPolicyRequest do
  #let(:instance) { Authentik::Api::ReputationPolicyRequest.new }

  describe 'test an instance of ReputationPolicyRequest' do
    it 'should create an instance of ReputationPolicyRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Authentik::Api::ReputationPolicyRequest)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "execution_logging"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "check_ip"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "check_username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "threshold"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
