=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # CaptchaStage Serializer
  class CaptchaStageRequest < ApiModelBase
    attr_accessor :name

    attr_accessor :flow_set

    # Public key, acquired your captcha Provider.
    attr_accessor :public_key

    # Private key, acquired your captcha Provider.
    attr_accessor :private_key

    attr_accessor :js_url

    attr_accessor :api_url

    attr_accessor :interactive

    attr_accessor :score_min_threshold

    attr_accessor :score_max_threshold

    # When enabled and the received captcha score is outside of the given threshold, the stage will show an error message. When not enabled, the flow will continue, but the data from the captcha will be available in the context for policy decisions
    attr_accessor :error_on_invalid_score

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'flow_set' => :'flow_set',
        :'public_key' => :'public_key',
        :'private_key' => :'private_key',
        :'js_url' => :'js_url',
        :'api_url' => :'api_url',
        :'interactive' => :'interactive',
        :'score_min_threshold' => :'score_min_threshold',
        :'score_max_threshold' => :'score_max_threshold',
        :'error_on_invalid_score' => :'error_on_invalid_score'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'flow_set' => :'Array<FlowSetRequest>',
        :'public_key' => :'String',
        :'private_key' => :'String',
        :'js_url' => :'String',
        :'api_url' => :'String',
        :'interactive' => :'Boolean',
        :'score_min_threshold' => :'Float',
        :'score_max_threshold' => :'Float',
        :'error_on_invalid_score' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::CaptchaStageRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::CaptchaStageRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'flow_set')
        if (value = attributes[:'flow_set']).is_a?(Array)
          self.flow_set = value
        end
      end

      if attributes.key?(:'public_key')
        self.public_key = attributes[:'public_key']
      else
        self.public_key = nil
      end

      if attributes.key?(:'private_key')
        self.private_key = attributes[:'private_key']
      else
        self.private_key = nil
      end

      if attributes.key?(:'js_url')
        self.js_url = attributes[:'js_url']
      end

      if attributes.key?(:'api_url')
        self.api_url = attributes[:'api_url']
      end

      if attributes.key?(:'interactive')
        self.interactive = attributes[:'interactive']
      end

      if attributes.key?(:'score_min_threshold')
        self.score_min_threshold = attributes[:'score_min_threshold']
      end

      if attributes.key?(:'score_max_threshold')
        self.score_max_threshold = attributes[:'score_max_threshold']
      end

      if attributes.key?(:'error_on_invalid_score')
        self.error_on_invalid_score = attributes[:'error_on_invalid_score']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if @public_key.nil?
        invalid_properties.push('invalid value for "public_key", public_key cannot be nil.')
      end

      if @public_key.to_s.length < 1
        invalid_properties.push('invalid value for "public_key", the character length must be greater than or equal to 1.')
      end

      if @private_key.nil?
        invalid_properties.push('invalid value for "private_key", private_key cannot be nil.')
      end

      if @private_key.to_s.length < 1
        invalid_properties.push('invalid value for "private_key", the character length must be greater than or equal to 1.')
      end

      if !@js_url.nil? && @js_url.to_s.length < 1
        invalid_properties.push('invalid value for "js_url", the character length must be greater than or equal to 1.')
      end

      if !@api_url.nil? && @api_url.to_s.length < 1
        invalid_properties.push('invalid value for "api_url", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length < 1
      return false if @public_key.nil?
      return false if @public_key.to_s.length < 1
      return false if @private_key.nil?
      return false if @private_key.to_s.length < 1
      return false if !@js_url.nil? && @js_url.to_s.length < 1
      return false if !@api_url.nil? && @api_url.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] public_key Value to be assigned
    def public_key=(public_key)
      if public_key.nil?
        fail ArgumentError, 'public_key cannot be nil'
      end

      if public_key.to_s.length < 1
        fail ArgumentError, 'invalid value for "public_key", the character length must be greater than or equal to 1.'
      end

      @public_key = public_key
    end

    # Custom attribute writer method with validation
    # @param [Object] private_key Value to be assigned
    def private_key=(private_key)
      if private_key.nil?
        fail ArgumentError, 'private_key cannot be nil'
      end

      if private_key.to_s.length < 1
        fail ArgumentError, 'invalid value for "private_key", the character length must be greater than or equal to 1.'
      end

      @private_key = private_key
    end

    # Custom attribute writer method with validation
    # @param [Object] js_url Value to be assigned
    def js_url=(js_url)
      if js_url.nil?
        fail ArgumentError, 'js_url cannot be nil'
      end

      if js_url.to_s.length < 1
        fail ArgumentError, 'invalid value for "js_url", the character length must be greater than or equal to 1.'
      end

      @js_url = js_url
    end

    # Custom attribute writer method with validation
    # @param [Object] api_url Value to be assigned
    def api_url=(api_url)
      if api_url.nil?
        fail ArgumentError, 'api_url cannot be nil'
      end

      if api_url.to_s.length < 1
        fail ArgumentError, 'invalid value for "api_url", the character length must be greater than or equal to 1.'
      end

      @api_url = api_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          flow_set == o.flow_set &&
          public_key == o.public_key &&
          private_key == o.private_key &&
          js_url == o.js_url &&
          api_url == o.api_url &&
          interactive == o.interactive &&
          score_min_threshold == o.score_min_threshold &&
          score_max_threshold == o.score_max_threshold &&
          error_on_invalid_score == o.error_on_invalid_score
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, flow_set, public_key, private_key, js_url, api_url, interactive, score_min_threshold, score_max_threshold, error_on_invalid_score].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
