=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Serializer for an active FlowPlan
  class FlowInspectorPlan < ApiModelBase
    attr_accessor :current_stage

    attr_accessor :next_planned_stage

    # Get the plan's context, sanitized
    attr_accessor :plan_context

    # Get a unique session ID
    attr_accessor :session_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'current_stage' => :'current_stage',
        :'next_planned_stage' => :'next_planned_stage',
        :'plan_context' => :'plan_context',
        :'session_id' => :'session_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'current_stage' => :'FlowStageBinding',
        :'next_planned_stage' => :'FlowStageBinding',
        :'plan_context' => :'Hash<String, Object>',
        :'session_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::FlowInspectorPlan` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::FlowInspectorPlan`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'current_stage')
        self.current_stage = attributes[:'current_stage']
      else
        self.current_stage = nil
      end

      if attributes.key?(:'next_planned_stage')
        self.next_planned_stage = attributes[:'next_planned_stage']
      else
        self.next_planned_stage = nil
      end

      if attributes.key?(:'plan_context')
        if (value = attributes[:'plan_context']).is_a?(Hash)
          self.plan_context = value
        end
      else
        self.plan_context = nil
      end

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      else
        self.session_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @current_stage.nil?
        invalid_properties.push('invalid value for "current_stage", current_stage cannot be nil.')
      end

      if @next_planned_stage.nil?
        invalid_properties.push('invalid value for "next_planned_stage", next_planned_stage cannot be nil.')
      end

      if @plan_context.nil?
        invalid_properties.push('invalid value for "plan_context", plan_context cannot be nil.')
      end

      if @session_id.nil?
        invalid_properties.push('invalid value for "session_id", session_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @current_stage.nil?
      return false if @next_planned_stage.nil?
      return false if @plan_context.nil?
      return false if @session_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] current_stage Value to be assigned
    def current_stage=(current_stage)
      if current_stage.nil?
        fail ArgumentError, 'current_stage cannot be nil'
      end

      @current_stage = current_stage
    end

    # Custom attribute writer method with validation
    # @param [Object] next_planned_stage Value to be assigned
    def next_planned_stage=(next_planned_stage)
      if next_planned_stage.nil?
        fail ArgumentError, 'next_planned_stage cannot be nil'
      end

      @next_planned_stage = next_planned_stage
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_context Value to be assigned
    def plan_context=(plan_context)
      if plan_context.nil?
        fail ArgumentError, 'plan_context cannot be nil'
      end

      @plan_context = plan_context
    end

    # Custom attribute writer method with validation
    # @param [Object] session_id Value to be assigned
    def session_id=(session_id)
      if session_id.nil?
        fail ArgumentError, 'session_id cannot be nil'
      end

      @session_id = session_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          current_stage == o.current_stage &&
          next_planned_stage == o.next_planned_stage &&
          plan_context == o.plan_context &&
          session_id == o.session_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [current_stage, next_planned_stage, plan_context, session_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
