=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Counts of active users added within a date range.
  class LicenseUserCountRange < ApiModelBase
    attr_accessor :start

    attr_accessor :_end

    attr_accessor :interval

    attr_accessor :internal_users_added

    attr_accessor :external_users_added

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'start' => :'start',
        :'_end' => :'end',
        :'interval' => :'interval',
        :'internal_users_added' => :'internal_users_added',
        :'external_users_added' => :'external_users_added'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'start' => :'Time',
        :'_end' => :'Time',
        :'interval' => :'String',
        :'internal_users_added' => :'Integer',
        :'external_users_added' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'interval',
      ])
    end

    # Returns attribute type mapping
    def self.acceptable_openapi_types
      openapi_types
    end

    # Returns the nullable attributes
    def self.acceptable_openapi_nullable
      openapi_nullable
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::LicenseUserCountRange` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::LicenseUserCountRange`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'start')
        self.start = attributes[:'start']
      else
        self.start = nil
      end

      if attributes.key?(:'_end')
        self._end = attributes[:'_end']
      else
        self._end = nil
      end

      if attributes.key?(:'interval')
        self.interval = attributes[:'interval']
      else
        self.interval = nil
      end

      if attributes.key?(:'internal_users_added')
        self.internal_users_added = attributes[:'internal_users_added']
      else
        self.internal_users_added = nil
      end

      if attributes.key?(:'external_users_added')
        self.external_users_added = attributes[:'external_users_added']
      else
        self.external_users_added = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @start.nil?
        invalid_properties.push('invalid value for "start", start cannot be nil.')
      end

      if @_end.nil?
        invalid_properties.push('invalid value for "_end", _end cannot be nil.')
      end

      if @internal_users_added.nil?
        invalid_properties.push('invalid value for "internal_users_added", internal_users_added cannot be nil.')
      end

      if @external_users_added.nil?
        invalid_properties.push('invalid value for "external_users_added", external_users_added cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @start.nil?
      return false if @_end.nil?
      return false if @internal_users_added.nil?
      return false if @external_users_added.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] start Value to be assigned
    def start=(start)
      if start.nil?
        fail ArgumentError, 'start cannot be nil'
      end

      @start = start
    end

    # Custom attribute writer method with validation
    # @param [Object] _end Value to be assigned
    def _end=(_end)
      if _end.nil?
        fail ArgumentError, '_end cannot be nil'
      end

      @_end = _end
    end

    # Custom attribute writer method with validation
    # @param [Object] internal_users_added Value to be assigned
    def internal_users_added=(internal_users_added)
      if internal_users_added.nil?
        fail ArgumentError, 'internal_users_added cannot be nil'
      end

      @internal_users_added = internal_users_added
    end

    # Custom attribute writer method with validation
    # @param [Object] external_users_added Value to be assigned
    def external_users_added=(external_users_added)
      if external_users_added.nil?
        fail ArgumentError, 'external_users_added cannot be nil'
      end

      @external_users_added = external_users_added
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          start == o.start &&
          _end == o._end &&
          interval == o.interval &&
          internal_users_added == o.internal_users_added &&
          external_users_added == o.external_users_added
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [start, _end, interval, internal_users_added, external_users_added].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      # include attributes inherited from allOf parents (the nearest declaration wins)
      map = acceptable_attribute_map
      transformed_hash = {}
      acceptable_openapi_types.each_pair do |key, type|
        if attributes.key?(map[key]) && attributes[map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      # include attributes inherited from allOf parents (the nearest declaration wins)
      self.class.acceptable_attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.acceptable_openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
