=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # MutualTLSStage Serializer
  class MutualTLSStage < ApiModelBase
    attr_accessor :pk

    attr_accessor :name

    # Get object type so that we know how to edit the object
    attr_accessor :component

    # Return object's verbose_name
    attr_accessor :verbose_name

    # Return object's plural verbose_name
    attr_accessor :verbose_name_plural

    # Return internal model name
    attr_accessor :meta_model_name

    attr_accessor :flow_set

    attr_accessor :mode

    # Configure certificate authorities to validate the certificate against. This option has a higher priority than the `client_certificate` option on `Brand`.
    attr_accessor :certificate_authorities

    attr_accessor :cert_attribute

    attr_accessor :user_attribute

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pk' => :'pk',
        :'name' => :'name',
        :'component' => :'component',
        :'verbose_name' => :'verbose_name',
        :'verbose_name_plural' => :'verbose_name_plural',
        :'meta_model_name' => :'meta_model_name',
        :'flow_set' => :'flow_set',
        :'mode' => :'mode',
        :'certificate_authorities' => :'certificate_authorities',
        :'cert_attribute' => :'cert_attribute',
        :'user_attribute' => :'user_attribute'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pk' => :'String',
        :'name' => :'String',
        :'component' => :'String',
        :'verbose_name' => :'String',
        :'verbose_name_plural' => :'String',
        :'meta_model_name' => :'String',
        :'flow_set' => :'Array<FlowSet>',
        :'mode' => :'StageModeEnum',
        :'certificate_authorities' => :'Array<String>',
        :'cert_attribute' => :'CertAttributeEnum',
        :'user_attribute' => :'UserAttributeEnum'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::MutualTLSStage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::MutualTLSStage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pk')
        self.pk = attributes[:'pk']
      else
        self.pk = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'component')
        self.component = attributes[:'component']
      else
        self.component = nil
      end

      if attributes.key?(:'verbose_name')
        self.verbose_name = attributes[:'verbose_name']
      else
        self.verbose_name = nil
      end

      if attributes.key?(:'verbose_name_plural')
        self.verbose_name_plural = attributes[:'verbose_name_plural']
      else
        self.verbose_name_plural = nil
      end

      if attributes.key?(:'meta_model_name')
        self.meta_model_name = attributes[:'meta_model_name']
      else
        self.meta_model_name = nil
      end

      if attributes.key?(:'flow_set')
        if (value = attributes[:'flow_set']).is_a?(Array)
          self.flow_set = value
        end
      else
        self.flow_set = nil
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'certificate_authorities')
        if (value = attributes[:'certificate_authorities']).is_a?(Array)
          self.certificate_authorities = value
        end
      end

      if attributes.key?(:'cert_attribute')
        self.cert_attribute = attributes[:'cert_attribute']
      else
        self.cert_attribute = nil
      end

      if attributes.key?(:'user_attribute')
        self.user_attribute = attributes[:'user_attribute']
      else
        self.user_attribute = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pk.nil?
        invalid_properties.push('invalid value for "pk", pk cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @component.nil?
        invalid_properties.push('invalid value for "component", component cannot be nil.')
      end

      if @verbose_name.nil?
        invalid_properties.push('invalid value for "verbose_name", verbose_name cannot be nil.')
      end

      if @verbose_name_plural.nil?
        invalid_properties.push('invalid value for "verbose_name_plural", verbose_name_plural cannot be nil.')
      end

      if @meta_model_name.nil?
        invalid_properties.push('invalid value for "meta_model_name", meta_model_name cannot be nil.')
      end

      if @flow_set.nil?
        invalid_properties.push('invalid value for "flow_set", flow_set cannot be nil.')
      end

      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      if @cert_attribute.nil?
        invalid_properties.push('invalid value for "cert_attribute", cert_attribute cannot be nil.')
      end

      if @user_attribute.nil?
        invalid_properties.push('invalid value for "user_attribute", user_attribute cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pk.nil?
      return false if @name.nil?
      return false if @component.nil?
      return false if @verbose_name.nil?
      return false if @verbose_name_plural.nil?
      return false if @meta_model_name.nil?
      return false if @flow_set.nil?
      return false if @mode.nil?
      return false if @cert_attribute.nil?
      return false if @user_attribute.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pk Value to be assigned
    def pk=(pk)
      if pk.nil?
        fail ArgumentError, 'pk cannot be nil'
      end

      @pk = pk
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] component Value to be assigned
    def component=(component)
      if component.nil?
        fail ArgumentError, 'component cannot be nil'
      end

      @component = component
    end

    # Custom attribute writer method with validation
    # @param [Object] verbose_name Value to be assigned
    def verbose_name=(verbose_name)
      if verbose_name.nil?
        fail ArgumentError, 'verbose_name cannot be nil'
      end

      @verbose_name = verbose_name
    end

    # Custom attribute writer method with validation
    # @param [Object] verbose_name_plural Value to be assigned
    def verbose_name_plural=(verbose_name_plural)
      if verbose_name_plural.nil?
        fail ArgumentError, 'verbose_name_plural cannot be nil'
      end

      @verbose_name_plural = verbose_name_plural
    end

    # Custom attribute writer method with validation
    # @param [Object] meta_model_name Value to be assigned
    def meta_model_name=(meta_model_name)
      if meta_model_name.nil?
        fail ArgumentError, 'meta_model_name cannot be nil'
      end

      @meta_model_name = meta_model_name
    end

    # Custom attribute writer method with validation
    # @param [Object] flow_set Value to be assigned
    def flow_set=(flow_set)
      if flow_set.nil?
        fail ArgumentError, 'flow_set cannot be nil'
      end

      @flow_set = flow_set
    end

    # Custom attribute writer method with validation
    # @param [Object] mode Value to be assigned
    def mode=(mode)
      if mode.nil?
        fail ArgumentError, 'mode cannot be nil'
      end

      @mode = mode
    end

    # Custom attribute writer method with validation
    # @param [Object] cert_attribute Value to be assigned
    def cert_attribute=(cert_attribute)
      if cert_attribute.nil?
        fail ArgumentError, 'cert_attribute cannot be nil'
      end

      @cert_attribute = cert_attribute
    end

    # Custom attribute writer method with validation
    # @param [Object] user_attribute Value to be assigned
    def user_attribute=(user_attribute)
      if user_attribute.nil?
        fail ArgumentError, 'user_attribute cannot be nil'
      end

      @user_attribute = user_attribute
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pk == o.pk &&
          name == o.name &&
          component == o.component &&
          verbose_name == o.verbose_name &&
          verbose_name_plural == o.verbose_name_plural &&
          meta_model_name == o.meta_model_name &&
          flow_set == o.flow_set &&
          mode == o.mode &&
          certificate_authorities == o.certificate_authorities &&
          cert_attribute == o.cert_attribute &&
          user_attribute == o.user_attribute
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pk, name, component, verbose_name, verbose_name_plural, meta_model_name, flow_set, mode, certificate_authorities, cert_attribute, user_attribute].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
