=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  class OutgoingSyncDeleteAction
    DO_NOTHING = "do_nothing".freeze
    DELETE = "delete".freeze
    SUSPEND = "suspend".freeze

    def self.all_vars
      @all_vars ||= [DO_NOTHING, DELETE, SUSPEND].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OutgoingSyncDeleteAction.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OutgoingSyncDeleteAction"
    end
  end
end
