=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Prompt Serializer
  class PatchedPromptRequest < ApiModelBase
    attr_accessor :name

    # Name of the form field, also used to store the value
    attr_accessor :field_key

    attr_accessor :label

    attr_accessor :type

    attr_accessor :required

    # Optionally provide a short hint that describes the expected input value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple choices.
    attr_accessor :placeholder

    # Optionally pre-fill the input with an initial value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple default choices.
    attr_accessor :initial_value

    attr_accessor :order

    attr_accessor :sub_text

    attr_accessor :placeholder_expression

    attr_accessor :initial_value_expression

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'field_key' => :'field_key',
        :'label' => :'label',
        :'type' => :'type',
        :'required' => :'required',
        :'placeholder' => :'placeholder',
        :'initial_value' => :'initial_value',
        :'order' => :'order',
        :'sub_text' => :'sub_text',
        :'placeholder_expression' => :'placeholder_expression',
        :'initial_value_expression' => :'initial_value_expression'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'field_key' => :'String',
        :'label' => :'String',
        :'type' => :'PromptTypeEnum',
        :'required' => :'Boolean',
        :'placeholder' => :'String',
        :'initial_value' => :'String',
        :'order' => :'Integer',
        :'sub_text' => :'String',
        :'placeholder_expression' => :'Boolean',
        :'initial_value_expression' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::PatchedPromptRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::PatchedPromptRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'field_key')
        self.field_key = attributes[:'field_key']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'required')
        self.required = attributes[:'required']
      end

      if attributes.key?(:'placeholder')
        self.placeholder = attributes[:'placeholder']
      end

      if attributes.key?(:'initial_value')
        self.initial_value = attributes[:'initial_value']
      end

      if attributes.key?(:'order')
        self.order = attributes[:'order']
      end

      if attributes.key?(:'sub_text')
        self.sub_text = attributes[:'sub_text']
      end

      if attributes.key?(:'placeholder_expression')
        self.placeholder_expression = attributes[:'placeholder_expression']
      end

      if attributes.key?(:'initial_value_expression')
        self.initial_value_expression = attributes[:'initial_value_expression']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@name.nil? && @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@field_key.nil? && @field_key.to_s.length < 1
        invalid_properties.push('invalid value for "field_key", the character length must be greater than or equal to 1.')
      end

      if !@label.nil? && @label.to_s.length < 1
        invalid_properties.push('invalid value for "label", the character length must be greater than or equal to 1.')
      end

      if !@order.nil? && @order > 2147483647
        invalid_properties.push('invalid value for "order", must be smaller than or equal to 2147483647.')
      end

      if !@order.nil? && @order < -2147483648
        invalid_properties.push('invalid value for "order", must be greater than or equal to -2147483648.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@name.nil? && @name.to_s.length < 1
      return false if !@field_key.nil? && @field_key.to_s.length < 1
      return false if !@label.nil? && @label.to_s.length < 1
      return false if !@order.nil? && @order > 2147483647
      return false if !@order.nil? && @order < -2147483648
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] field_key Value to be assigned
    def field_key=(field_key)
      if field_key.nil?
        fail ArgumentError, 'field_key cannot be nil'
      end

      if field_key.to_s.length < 1
        fail ArgumentError, 'invalid value for "field_key", the character length must be greater than or equal to 1.'
      end

      @field_key = field_key
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      if label.to_s.length < 1
        fail ArgumentError, 'invalid value for "label", the character length must be greater than or equal to 1.'
      end

      @label = label
    end

    # Custom attribute writer method with validation
    # @param [Object] order Value to be assigned
    def order=(order)
      if order.nil?
        fail ArgumentError, 'order cannot be nil'
      end

      if order > 2147483647
        fail ArgumentError, 'invalid value for "order", must be smaller than or equal to 2147483647.'
      end

      if order < -2147483648
        fail ArgumentError, 'invalid value for "order", must be greater than or equal to -2147483648.'
      end

      @order = order
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          field_key == o.field_key &&
          label == o.label &&
          type == o.type &&
          required == o.required &&
          placeholder == o.placeholder &&
          initial_value == o.initial_value &&
          order == o.order &&
          sub_text == o.sub_text &&
          placeholder_expression == o.placeholder_expression &&
          initial_value_expression == o.initial_value_expression
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, field_key, label, type, required, placeholder, initial_value, order, sub_text, placeholder_expression, initial_value_expression].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
