=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # EmailStage Serializer
  class PatchedEmailStageRequest < ApiModelBase
    attr_accessor :name

    attr_accessor :flow_set

    # When enabled, global Email connection settings will be used and connection settings below will be ignored.
    attr_accessor :use_global_settings

    attr_accessor :host

    attr_accessor :port

    attr_accessor :username

    attr_accessor :password

    attr_accessor :use_tls

    attr_accessor :use_ssl

    attr_accessor :timeout

    attr_accessor :from_address

    # Time in minutes the token sent is valid.
    attr_accessor :token_expiry

    attr_accessor :subject

    attr_accessor :template

    # Activate users upon completion of stage.
    attr_accessor :activate_user_on_success

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'flow_set' => :'flow_set',
        :'use_global_settings' => :'use_global_settings',
        :'host' => :'host',
        :'port' => :'port',
        :'username' => :'username',
        :'password' => :'password',
        :'use_tls' => :'use_tls',
        :'use_ssl' => :'use_ssl',
        :'timeout' => :'timeout',
        :'from_address' => :'from_address',
        :'token_expiry' => :'token_expiry',
        :'subject' => :'subject',
        :'template' => :'template',
        :'activate_user_on_success' => :'activate_user_on_success'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'flow_set' => :'Array<FlowSetRequest>',
        :'use_global_settings' => :'Boolean',
        :'host' => :'String',
        :'port' => :'Integer',
        :'username' => :'String',
        :'password' => :'String',
        :'use_tls' => :'Boolean',
        :'use_ssl' => :'Boolean',
        :'timeout' => :'Integer',
        :'from_address' => :'String',
        :'token_expiry' => :'Integer',
        :'subject' => :'String',
        :'template' => :'String',
        :'activate_user_on_success' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::PatchedEmailStageRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::PatchedEmailStageRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'flow_set')
        if (value = attributes[:'flow_set']).is_a?(Array)
          self.flow_set = value
        end
      end

      if attributes.key?(:'use_global_settings')
        self.use_global_settings = attributes[:'use_global_settings']
      end

      if attributes.key?(:'host')
        self.host = attributes[:'host']
      end

      if attributes.key?(:'port')
        self.port = attributes[:'port']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'password')
        self.password = attributes[:'password']
      end

      if attributes.key?(:'use_tls')
        self.use_tls = attributes[:'use_tls']
      end

      if attributes.key?(:'use_ssl')
        self.use_ssl = attributes[:'use_ssl']
      end

      if attributes.key?(:'timeout')
        self.timeout = attributes[:'timeout']
      end

      if attributes.key?(:'from_address')
        self.from_address = attributes[:'from_address']
      end

      if attributes.key?(:'token_expiry')
        self.token_expiry = attributes[:'token_expiry']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'template')
        self.template = attributes[:'template']
      end

      if attributes.key?(:'activate_user_on_success')
        self.activate_user_on_success = attributes[:'activate_user_on_success']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@name.nil? && @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if !@host.nil? && @host.to_s.length < 1
        invalid_properties.push('invalid value for "host", the character length must be greater than or equal to 1.')
      end

      if !@port.nil? && @port > 2147483647
        invalid_properties.push('invalid value for "port", must be smaller than or equal to 2147483647.')
      end

      if !@port.nil? && @port < -2147483648
        invalid_properties.push('invalid value for "port", must be greater than or equal to -2147483648.')
      end

      if !@timeout.nil? && @timeout > 2147483647
        invalid_properties.push('invalid value for "timeout", must be smaller than or equal to 2147483647.')
      end

      if !@timeout.nil? && @timeout < -2147483648
        invalid_properties.push('invalid value for "timeout", must be greater than or equal to -2147483648.')
      end

      if !@from_address.nil? && @from_address.to_s.length > 254
        invalid_properties.push('invalid value for "from_address", the character length must be smaller than or equal to 254.')
      end

      if !@from_address.nil? && @from_address.to_s.length < 1
        invalid_properties.push('invalid value for "from_address", the character length must be greater than or equal to 1.')
      end

      if !@token_expiry.nil? && @token_expiry > 2147483647
        invalid_properties.push('invalid value for "token_expiry", must be smaller than or equal to 2147483647.')
      end

      if !@token_expiry.nil? && @token_expiry < -2147483648
        invalid_properties.push('invalid value for "token_expiry", must be greater than or equal to -2147483648.')
      end

      if !@subject.nil? && @subject.to_s.length < 1
        invalid_properties.push('invalid value for "subject", the character length must be greater than or equal to 1.')
      end

      if !@template.nil? && @template.to_s.length < 1
        invalid_properties.push('invalid value for "template", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@name.nil? && @name.to_s.length < 1
      return false if !@host.nil? && @host.to_s.length < 1
      return false if !@port.nil? && @port > 2147483647
      return false if !@port.nil? && @port < -2147483648
      return false if !@timeout.nil? && @timeout > 2147483647
      return false if !@timeout.nil? && @timeout < -2147483648
      return false if !@from_address.nil? && @from_address.to_s.length > 254
      return false if !@from_address.nil? && @from_address.to_s.length < 1
      return false if !@token_expiry.nil? && @token_expiry > 2147483647
      return false if !@token_expiry.nil? && @token_expiry < -2147483648
      return false if !@subject.nil? && @subject.to_s.length < 1
      return false if !@template.nil? && @template.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] host Value to be assigned
    def host=(host)
      if host.nil?
        fail ArgumentError, 'host cannot be nil'
      end

      if host.to_s.length < 1
        fail ArgumentError, 'invalid value for "host", the character length must be greater than or equal to 1.'
      end

      @host = host
    end

    # Custom attribute writer method with validation
    # @param [Object] port Value to be assigned
    def port=(port)
      if port.nil?
        fail ArgumentError, 'port cannot be nil'
      end

      if port > 2147483647
        fail ArgumentError, 'invalid value for "port", must be smaller than or equal to 2147483647.'
      end

      if port < -2147483648
        fail ArgumentError, 'invalid value for "port", must be greater than or equal to -2147483648.'
      end

      @port = port
    end

    # Custom attribute writer method with validation
    # @param [Object] timeout Value to be assigned
    def timeout=(timeout)
      if timeout.nil?
        fail ArgumentError, 'timeout cannot be nil'
      end

      if timeout > 2147483647
        fail ArgumentError, 'invalid value for "timeout", must be smaller than or equal to 2147483647.'
      end

      if timeout < -2147483648
        fail ArgumentError, 'invalid value for "timeout", must be greater than or equal to -2147483648.'
      end

      @timeout = timeout
    end

    # Custom attribute writer method with validation
    # @param [Object] from_address Value to be assigned
    def from_address=(from_address)
      if from_address.nil?
        fail ArgumentError, 'from_address cannot be nil'
      end

      if from_address.to_s.length > 254
        fail ArgumentError, 'invalid value for "from_address", the character length must be smaller than or equal to 254.'
      end

      if from_address.to_s.length < 1
        fail ArgumentError, 'invalid value for "from_address", the character length must be greater than or equal to 1.'
      end

      @from_address = from_address
    end

    # Custom attribute writer method with validation
    # @param [Object] token_expiry Value to be assigned
    def token_expiry=(token_expiry)
      if token_expiry.nil?
        fail ArgumentError, 'token_expiry cannot be nil'
      end

      if token_expiry > 2147483647
        fail ArgumentError, 'invalid value for "token_expiry", must be smaller than or equal to 2147483647.'
      end

      if token_expiry < -2147483648
        fail ArgumentError, 'invalid value for "token_expiry", must be greater than or equal to -2147483648.'
      end

      @token_expiry = token_expiry
    end

    # Custom attribute writer method with validation
    # @param [Object] subject Value to be assigned
    def subject=(subject)
      if subject.nil?
        fail ArgumentError, 'subject cannot be nil'
      end

      if subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "subject", the character length must be greater than or equal to 1.'
      end

      @subject = subject
    end

    # Custom attribute writer method with validation
    # @param [Object] template Value to be assigned
    def template=(template)
      if template.nil?
        fail ArgumentError, 'template cannot be nil'
      end

      if template.to_s.length < 1
        fail ArgumentError, 'invalid value for "template", the character length must be greater than or equal to 1.'
      end

      @template = template
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          flow_set == o.flow_set &&
          use_global_settings == o.use_global_settings &&
          host == o.host &&
          port == o.port &&
          username == o.username &&
          password == o.password &&
          use_tls == o.use_tls &&
          use_ssl == o.use_ssl &&
          timeout == o.timeout &&
          from_address == o.from_address &&
          token_expiry == o.token_expiry &&
          subject == o.subject &&
          template == o.template &&
          activate_user_on_success == o.activate_user_on_success
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, flow_set, use_global_settings, host, port, username, password, use_tls, use_ssl, timeout, from_address, token_expiry, subject, template, activate_user_on_success].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
