=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Mixin to validate that a valid enterprise license exists before allowing to save the object
  class RequestRule < ApiModelBase
    attr_accessor :uuid

    attr_accessor :pbm_uuid

    attr_accessor :policy_engine_mode

    attr_accessor :name

    attr_accessor :targets

    attr_accessor :notification_transports

    attr_accessor :notification_mode

    attr_accessor :min_reviewers

    attr_accessor :min_reviewers_is_per_group

    attr_accessor :request_flow

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'pbm_uuid' => :'pbm_uuid',
        :'policy_engine_mode' => :'policy_engine_mode',
        :'name' => :'name',
        :'targets' => :'targets',
        :'notification_transports' => :'notification_transports',
        :'notification_mode' => :'notification_mode',
        :'min_reviewers' => :'min_reviewers',
        :'min_reviewers_is_per_group' => :'min_reviewers_is_per_group',
        :'request_flow' => :'request_flow'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'pbm_uuid' => :'String',
        :'policy_engine_mode' => :'PolicyEngineMode',
        :'name' => :'String',
        :'targets' => :'Array<String>',
        :'notification_transports' => :'Array<String>',
        :'notification_mode' => :'NotificationModeEnum',
        :'min_reviewers' => :'Integer',
        :'min_reviewers_is_per_group' => :'Boolean',
        :'request_flow' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'request_flow'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::RequestRule` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::RequestRule`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.key?(:'pbm_uuid')
        self.pbm_uuid = attributes[:'pbm_uuid']
      else
        self.pbm_uuid = nil
      end

      if attributes.key?(:'policy_engine_mode')
        self.policy_engine_mode = attributes[:'policy_engine_mode']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'targets')
        if (value = attributes[:'targets']).is_a?(Array)
          self.targets = value
        end
      else
        self.targets = nil
      end

      if attributes.key?(:'notification_transports')
        if (value = attributes[:'notification_transports']).is_a?(Array)
          self.notification_transports = value
        end
      end

      if attributes.key?(:'notification_mode')
        self.notification_mode = attributes[:'notification_mode']
      end

      if attributes.key?(:'min_reviewers')
        self.min_reviewers = attributes[:'min_reviewers']
      end

      if attributes.key?(:'min_reviewers_is_per_group')
        self.min_reviewers_is_per_group = attributes[:'min_reviewers_is_per_group']
      end

      if attributes.key?(:'request_flow')
        self.request_flow = attributes[:'request_flow']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pbm_uuid.nil?
        invalid_properties.push('invalid value for "pbm_uuid", pbm_uuid cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @targets.nil?
        invalid_properties.push('invalid value for "targets", targets cannot be nil.')
      end

      if !@min_reviewers.nil? && @min_reviewers > 32767
        invalid_properties.push('invalid value for "min_reviewers", must be smaller than or equal to 32767.')
      end

      if !@min_reviewers.nil? && @min_reviewers < 0
        invalid_properties.push('invalid value for "min_reviewers", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pbm_uuid.nil?
      return false if @name.nil?
      return false if @targets.nil?
      return false if !@min_reviewers.nil? && @min_reviewers > 32767
      return false if !@min_reviewers.nil? && @min_reviewers < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pbm_uuid Value to be assigned
    def pbm_uuid=(pbm_uuid)
      if pbm_uuid.nil?
        fail ArgumentError, 'pbm_uuid cannot be nil'
      end

      @pbm_uuid = pbm_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] targets Value to be assigned
    def targets=(targets)
      if targets.nil?
        fail ArgumentError, 'targets cannot be nil'
      end

      @targets = targets
    end

    # Custom attribute writer method with validation
    # @param [Object] min_reviewers Value to be assigned
    def min_reviewers=(min_reviewers)
      if min_reviewers.nil?
        fail ArgumentError, 'min_reviewers cannot be nil'
      end

      if min_reviewers > 32767
        fail ArgumentError, 'invalid value for "min_reviewers", must be smaller than or equal to 32767.'
      end

      if min_reviewers < 0
        fail ArgumentError, 'invalid value for "min_reviewers", must be greater than or equal to 0.'
      end

      @min_reviewers = min_reviewers
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          pbm_uuid == o.pbm_uuid &&
          policy_engine_mode == o.policy_engine_mode &&
          name == o.name &&
          targets == o.targets &&
          notification_transports == o.notification_transports &&
          notification_mode == o.notification_mode &&
          min_reviewers == o.min_reviewers &&
          min_reviewers_is_per_group == o.min_reviewers_is_per_group &&
          request_flow == o.request_flow
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, pbm_uuid, policy_engine_mode, name, targets, notification_transports, notification_mode, min_reviewers, min_reviewers_is_per_group, request_flow].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
