=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  class SamlVersionEnum
    N1_1 = "1.1".freeze
    N2_0 = "2.0".freeze

    def self.all_vars
      @all_vars ||= [N1_1, N2_0].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SamlVersionEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SamlVersionEnum"
    end
  end
end
