=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  class SAMLLogoutMethods
    FRONTCHANNEL_IFRAME = "frontchannel_iframe".freeze
    FRONTCHANNEL_NATIVE = "frontchannel_native".freeze
    BACKCHANNEL = "backchannel".freeze

    def self.all_vars
      @all_vars ||= [FRONTCHANNEL_IFRAME, FRONTCHANNEL_NATIVE, BACKCHANNEL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SAMLLogoutMethods.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SAMLLogoutMethods"
    end
  end
end
