=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Serializer for SourceType
  class SourceType < ApiModelBase
    attr_accessor :name

    attr_accessor :verbose_name

    attr_accessor :urls_customizable

    attr_accessor :request_token_url

    attr_accessor :authorization_url

    attr_accessor :access_token_url

    attr_accessor :profile_url

    attr_accessor :oidc_well_known_url

    attr_accessor :oidc_jwks_url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'verbose_name' => :'verbose_name',
        :'urls_customizable' => :'urls_customizable',
        :'request_token_url' => :'request_token_url',
        :'authorization_url' => :'authorization_url',
        :'access_token_url' => :'access_token_url',
        :'profile_url' => :'profile_url',
        :'oidc_well_known_url' => :'oidc_well_known_url',
        :'oidc_jwks_url' => :'oidc_jwks_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'verbose_name' => :'String',
        :'urls_customizable' => :'Boolean',
        :'request_token_url' => :'String',
        :'authorization_url' => :'String',
        :'access_token_url' => :'String',
        :'profile_url' => :'String',
        :'oidc_well_known_url' => :'String',
        :'oidc_jwks_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'request_token_url',
        :'authorization_url',
        :'access_token_url',
        :'profile_url',
        :'oidc_well_known_url',
        :'oidc_jwks_url'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::SourceType` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::SourceType`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'verbose_name')
        self.verbose_name = attributes[:'verbose_name']
      else
        self.verbose_name = nil
      end

      if attributes.key?(:'urls_customizable')
        self.urls_customizable = attributes[:'urls_customizable']
      else
        self.urls_customizable = nil
      end

      if attributes.key?(:'request_token_url')
        self.request_token_url = attributes[:'request_token_url']
      else
        self.request_token_url = nil
      end

      if attributes.key?(:'authorization_url')
        self.authorization_url = attributes[:'authorization_url']
      else
        self.authorization_url = nil
      end

      if attributes.key?(:'access_token_url')
        self.access_token_url = attributes[:'access_token_url']
      else
        self.access_token_url = nil
      end

      if attributes.key?(:'profile_url')
        self.profile_url = attributes[:'profile_url']
      else
        self.profile_url = nil
      end

      if attributes.key?(:'oidc_well_known_url')
        self.oidc_well_known_url = attributes[:'oidc_well_known_url']
      else
        self.oidc_well_known_url = nil
      end

      if attributes.key?(:'oidc_jwks_url')
        self.oidc_jwks_url = attributes[:'oidc_jwks_url']
      else
        self.oidc_jwks_url = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @verbose_name.nil?
        invalid_properties.push('invalid value for "verbose_name", verbose_name cannot be nil.')
      end

      if @urls_customizable.nil?
        invalid_properties.push('invalid value for "urls_customizable", urls_customizable cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @verbose_name.nil?
      return false if @urls_customizable.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] verbose_name Value to be assigned
    def verbose_name=(verbose_name)
      if verbose_name.nil?
        fail ArgumentError, 'verbose_name cannot be nil'
      end

      @verbose_name = verbose_name
    end

    # Custom attribute writer method with validation
    # @param [Object] urls_customizable Value to be assigned
    def urls_customizable=(urls_customizable)
      if urls_customizable.nil?
        fail ArgumentError, 'urls_customizable cannot be nil'
      end

      @urls_customizable = urls_customizable
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          verbose_name == o.verbose_name &&
          urls_customizable == o.urls_customizable &&
          request_token_url == o.request_token_url &&
          authorization_url == o.authorization_url &&
          access_token_url == o.access_token_url &&
          profile_url == o.profile_url &&
          oidc_well_known_url == o.oidc_well_known_url &&
          oidc_jwks_url == o.oidc_jwks_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, verbose_name, urls_customizable, request_token_url, authorization_url, access_token_url, profile_url, oidc_well_known_url, oidc_jwks_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
