=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Serialize TaskInfo and TaskResult
  class SystemTask < ApiModelBase
    attr_accessor :uuid

    attr_accessor :name

    # Get full name with UID
    attr_accessor :full_name

    attr_accessor :uid

    attr_accessor :description

    attr_accessor :start_timestamp

    attr_accessor :finish_timestamp

    attr_accessor :duration

    attr_accessor :status

    attr_accessor :messages

    attr_accessor :expires

    attr_accessor :expiring

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'name' => :'name',
        :'full_name' => :'full_name',
        :'uid' => :'uid',
        :'description' => :'description',
        :'start_timestamp' => :'start_timestamp',
        :'finish_timestamp' => :'finish_timestamp',
        :'duration' => :'duration',
        :'status' => :'status',
        :'messages' => :'messages',
        :'expires' => :'expires',
        :'expiring' => :'expiring'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'name' => :'String',
        :'full_name' => :'String',
        :'uid' => :'String',
        :'description' => :'String',
        :'start_timestamp' => :'Time',
        :'finish_timestamp' => :'Time',
        :'duration' => :'Float',
        :'status' => :'SystemTaskStatusEnum',
        :'messages' => :'Array<LogEvent>',
        :'expires' => :'Time',
        :'expiring' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'expires',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::SystemTask` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::SystemTask`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      else
        self.uuid = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'full_name')
        self.full_name = attributes[:'full_name']
      else
        self.full_name = nil
      end

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'start_timestamp')
        self.start_timestamp = attributes[:'start_timestamp']
      else
        self.start_timestamp = nil
      end

      if attributes.key?(:'finish_timestamp')
        self.finish_timestamp = attributes[:'finish_timestamp']
      else
        self.finish_timestamp = nil
      end

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      else
        self.duration = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'messages')
        if (value = attributes[:'messages']).is_a?(Array)
          self.messages = value
        end
      else
        self.messages = nil
      end

      if attributes.key?(:'expires')
        self.expires = attributes[:'expires']
      end

      if attributes.key?(:'expiring')
        self.expiring = attributes[:'expiring']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @uuid.nil?
        invalid_properties.push('invalid value for "uuid", uuid cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @full_name.nil?
        invalid_properties.push('invalid value for "full_name", full_name cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @start_timestamp.nil?
        invalid_properties.push('invalid value for "start_timestamp", start_timestamp cannot be nil.')
      end

      if @finish_timestamp.nil?
        invalid_properties.push('invalid value for "finish_timestamp", finish_timestamp cannot be nil.')
      end

      if @duration.nil?
        invalid_properties.push('invalid value for "duration", duration cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @messages.nil?
        invalid_properties.push('invalid value for "messages", messages cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @uuid.nil?
      return false if @name.nil?
      return false if @full_name.nil?
      return false if @description.nil?
      return false if @start_timestamp.nil?
      return false if @finish_timestamp.nil?
      return false if @duration.nil?
      return false if @status.nil?
      return false if @messages.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      @uuid = uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] full_name Value to be assigned
    def full_name=(full_name)
      if full_name.nil?
        fail ArgumentError, 'full_name cannot be nil'
      end

      @full_name = full_name
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] start_timestamp Value to be assigned
    def start_timestamp=(start_timestamp)
      if start_timestamp.nil?
        fail ArgumentError, 'start_timestamp cannot be nil'
      end

      @start_timestamp = start_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] finish_timestamp Value to be assigned
    def finish_timestamp=(finish_timestamp)
      if finish_timestamp.nil?
        fail ArgumentError, 'finish_timestamp cannot be nil'
      end

      @finish_timestamp = finish_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] duration Value to be assigned
    def duration=(duration)
      if duration.nil?
        fail ArgumentError, 'duration cannot be nil'
      end

      @duration = duration
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] messages Value to be assigned
    def messages=(messages)
      if messages.nil?
        fail ArgumentError, 'messages cannot be nil'
      end

      @messages = messages
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          name == o.name &&
          full_name == o.full_name &&
          uid == o.uid &&
          description == o.description &&
          start_timestamp == o.start_timestamp &&
          finish_timestamp == o.finish_timestamp &&
          duration == o.duration &&
          status == o.status &&
          messages == o.messages &&
          expires == o.expires &&
          expiring == o.expiring
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, name, full_name, uid, description, start_timestamp, finish_timestamp, duration, status, messages, expires, expiring].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
