=begin
This file is automatically generated by: https://openapi-generator.tech.
Any manual changes will be lost when the OpenAPI scheme changes.

=end

require 'date'
require 'time'

module Authentik::Api
  # Mixin to validate that a valid enterprise license exists before allowing to save the object
  class UserOffboarding < ApiModelBase
    attr_accessor :id

    attr_accessor :user

    attr_accessor :user_obj

    # Absolute time at which the offboarding action is executed.
    attr_accessor :scheduled_at

    attr_accessor :action

    # Revoke all of the user's sessions when offboarding.
    attr_accessor :revoke_sessions

    # Revoke all of the user's tokens when offboarding.
    attr_accessor :revoke_tokens

    attr_accessor :status

    attr_accessor :created_by_obj

    attr_accessor :created_at

    attr_accessor :executed_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'user' => :'user',
        :'user_obj' => :'user_obj',
        :'scheduled_at' => :'scheduled_at',
        :'action' => :'action',
        :'revoke_sessions' => :'revoke_sessions',
        :'revoke_tokens' => :'revoke_tokens',
        :'status' => :'status',
        :'created_by_obj' => :'created_by_obj',
        :'created_at' => :'created_at',
        :'executed_at' => :'executed_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'user' => :'Integer',
        :'user_obj' => :'PartialUser',
        :'scheduled_at' => :'Time',
        :'action' => :'OffboardingActionEnum',
        :'revoke_sessions' => :'Boolean',
        :'revoke_tokens' => :'Boolean',
        :'status' => :'OffboardingStatusEnum',
        :'created_by_obj' => :'PartialUser',
        :'created_at' => :'Time',
        :'executed_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'executed_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Authentik::Api::UserOffboarding` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Authentik::Api::UserOffboarding`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      else
        self.user = nil
      end

      if attributes.key?(:'user_obj')
        self.user_obj = attributes[:'user_obj']
      else
        self.user_obj = nil
      end

      if attributes.key?(:'scheduled_at')
        self.scheduled_at = attributes[:'scheduled_at']
      else
        self.scheduled_at = nil
      end

      if attributes.key?(:'action')
        self.action = attributes[:'action']
      end

      if attributes.key?(:'revoke_sessions')
        self.revoke_sessions = attributes[:'revoke_sessions']
      end

      if attributes.key?(:'revoke_tokens')
        self.revoke_tokens = attributes[:'revoke_tokens']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_by_obj')
        self.created_by_obj = attributes[:'created_by_obj']
      else
        self.created_by_obj = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'executed_at')
        self.executed_at = attributes[:'executed_at']
      else
        self.executed_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @user_obj.nil?
        invalid_properties.push('invalid value for "user_obj", user_obj cannot be nil.')
      end

      if @scheduled_at.nil?
        invalid_properties.push('invalid value for "scheduled_at", scheduled_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @created_by_obj.nil?
        invalid_properties.push('invalid value for "created_by_obj", created_by_obj cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @user.nil?
      return false if @user_obj.nil?
      return false if @scheduled_at.nil?
      return false if @status.nil?
      return false if @created_by_obj.nil?
      return false if @created_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] user Value to be assigned
    def user=(user)
      if user.nil?
        fail ArgumentError, 'user cannot be nil'
      end

      @user = user
    end

    # Custom attribute writer method with validation
    # @param [Object] user_obj Value to be assigned
    def user_obj=(user_obj)
      if user_obj.nil?
        fail ArgumentError, 'user_obj cannot be nil'
      end

      @user_obj = user_obj
    end

    # Custom attribute writer method with validation
    # @param [Object] scheduled_at Value to be assigned
    def scheduled_at=(scheduled_at)
      if scheduled_at.nil?
        fail ArgumentError, 'scheduled_at cannot be nil'
      end

      @scheduled_at = scheduled_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] created_by_obj Value to be assigned
    def created_by_obj=(created_by_obj)
      if created_by_obj.nil?
        fail ArgumentError, 'created_by_obj cannot be nil'
      end

      @created_by_obj = created_by_obj
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          user == o.user &&
          user_obj == o.user_obj &&
          scheduled_at == o.scheduled_at &&
          action == o.action &&
          revoke_sessions == o.revoke_sessions &&
          revoke_tokens == o.revoke_tokens &&
          status == o.status &&
          created_by_obj == o.created_by_obj &&
          created_at == o.created_at &&
          executed_at == o.executed_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, user, user_obj, scheduled_at, action, revoke_sessions, revoke_tokens, status, created_by_obj, created_at, executed_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
