# Generates the OpenAPI client for an authentik release and opens a PR for review.
#
# 1. Review the PR and merge.
# 2. Tag release.
# 3. Publish gem.
#
# Keep this file in "sync" with `generate-openapi-client-main.yaml`.
name: Generate OpenAPI client (authentik release)

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: "The authentik version tag, e.g. 'version/2026.2.0'"
        required: true
        type: string
  workflow_call:
    inputs:
      tag-name:
        description: "The authentik version tag detected by the calling workflow."
        required: true
        type: string
    secrets:
      PAT:
        required: true

env:
  OPENAPI_GENERATOR_PATH: "tmp"

jobs:
  get-release-branch:
    permissions:
      contents: write
    uses: ./.github/workflows/get-release-branch.yaml
    with:
      schema-url: "https://raw.githubusercontent.com/goauthentik/authentik/${{ inputs.tag-name }}/schema.yml"

  build-client:
    permissions:
      contents: write
      pull-requests: write
    needs: get-release-branch
    runs-on: ubuntu-latest
    env:
      AUTHENTIK_VERSION: ${{ needs.get-release-branch.outputs.authentik-version }} # 2026.2.0-rc1
      GEM_VERSION: ${{ needs.get-release-branch.outputs.gem-version }} # 2026.2.0.rc1
      BASE_BRANCH: ${{ needs.get-release-branch.outputs.release-branch }} # 2026.2
    steps:
      - name: Checkout release branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.BASE_BRANCH }}
          persist-credentials: false

      - name: Download schema artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: schema
          path: ./.authentik/

      - name: Build OpenAPI client
        uses: ./.github/actions/build-openapi-client
        with:
          output-path: ${{ env.OPENAPI_GENERATOR_PATH }}
          config-file: ./.openapi-generator/config.yaml
          openapi-file: ./.authentik/schema.yaml
          templates-dir: ./.openapi-generator/ruby-templates
          gem-version: ${{ env.GEM_VERSION }}

      - name: Create pull request for release
        id: cpr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.PAT }} # Need separate token to trigger workflows. # zizmor: ignore[secrets-outside-env]
          commit-message: "Update OpenAPI client (${{ env.AUTHENTIK_VERSION }})"
          branch: "openapi-client-update/version/${{ env.AUTHENTIK_VERSION }}"
          base: "${{ needs.get-release-branch.outputs.release-branch }}"
          title: "OpenAPI client update (${{ env.AUTHENTIK_VERSION }})"
          body: |
            This PR updates the generated OpenAPI client to match the schema for authentik release `${{ env.AUTHENTIK_VERSION }}`.
  
            Authentik version: `${{ env.AUTHENTIK_VERSION }}`
            Gem version: `${{ env.GEM_VERSION }}`
            
            > Schema sourced from [goauthentik/authentik@version/${{ env.AUTHENTIK_VERSION }}](https://github.com/goauthentik/authentik/blob/version/${{ env.AUTHENTIK_VERSION }}/schema.yml)
          labels: release
          delete-branch: true
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
