# Monitors the `goauthentik/authentik` repository for `schema.yml` updates.
#
# When an update is found, it dispatches an OpenAPI client update workflow.
name: Poll schema.yml and dispatch builder

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 6AM UTC.
  workflow_dispatch:

jobs:
  check-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      schema-updated: ${{ steps.schema-diff.outputs.updated }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # Curl Options: Fail on HTTP errors; silent; show error on failure; follow redirects.
      - name: Fetch authentik's OpenAPI document
        run: curl -fsSL https://raw.githubusercontent.com/goauthentik/authentik/main/schema.yml -o /tmp/schema.yaml

      - name: Check for schema updates
        id: schema-diff
        run: |
          if diff -q /tmp/schema.yaml ./.authentik/schema.yaml; then
            echo "updated=false" >> "$GITHUB_OUTPUT"
          else
            echo "updated=true" >> "$GITHUB_OUTPUT"
          fi

  dispatch-update:
    needs: check-schema
    if: needs.check-schema.outputs.schema-updated == 'true'
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/generate-openapi-client-main.yaml
