# Monitors the `goauthentik/authentik` repository for new tags.
#
# When new tags are found:
# * Compares against known tags (a branch with the same name exists).
# * Dispatches builder workflows for unknown tags.
name: Poll tags and dispatch builders

on:
  schedule:
    - cron: "15 6 * * *"
  workflow_dispatch:

env:
  SOURCE_OWNER: goauthentik
  SOURCE_REPO: authentik
  SOURCE_LATEST_TAGS_NUM: 1
  AUTO_PR_BRANCH_PREFIX: "openapi-client-update/"

jobs:
  check-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - id: get-branches
        name: Get local branches
        run: |
          BRANCHES=$(git branch --remotes --format='%(refname:short)' | sed -E 's/^origin\/?//' | awk NF | jq -Rnc '[inputs]')
          echo "BRANCHES=$BRANCHES" >> "$GITHUB_ENV"

      - id: get-tags
        name: Get local tags
        run: |
          TAGS=$(git tag | jq -Rnc '[inputs]')
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"          

      - id: get-missing-tags
        name: Get missing authentik tags
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // authentik
            const owner = process.env.SOURCE_OWNER;
            const repo = process.env.SOURCE_REPO;
            const lookupTagsNum = process.env.SOURCE_LATEST_TAGS_NUM;
            const response = await github.rest.repos.listTags({owner, repo, per_page: lookupTagsNum});
            const akTags = response.data.map(t => t.name); // e.g., `version/2026.2.2-rc2`
            
            // authentik-api
            const prBranchPrefix = process.env.AUTO_PR_BRANCH_PREFIX;           
            const branches = JSON.parse(process.env.BRANCHES);
            const tags = JSON.parse(process.env.TAGS);
            
            // Remove authentik tags that already exist as a tag or PR branch in this repo.
            // authentik tag: `version/2026.2.2-rc2`
            // branch: `openapi-client-update/version/2026.2.2-rc2`
            // tag: `v2026.2.2.rc2`
            const filteredTags = akTags.filter(
              akTag => akTag.startsWith('version/') && 
                !branches.includes(`${prBranchPrefix}${akTag}`) &&
                !tags.includes('v' + akTag.replace('version/', '').replace('-', '.'))
            );
            
            core.setOutput('tags', JSON.stringify(filteredTags));
            core.info(`New tags: ${filteredTags.join(', ')}`);

      - id: set-tags
        name: Set tags
        env:
          TAGS_JSON: ${{ steps.get-missing-tags.outputs.tags }}
        run: |
          {
            echo "tags<<JSON"
            echo "$TAGS_JSON"
            echo "JSON"
          } >> "$GITHUB_OUTPUT"

  dispatch-update:
    needs: check-tags
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.check-tags.outputs.tags != '[]' }}
    strategy:
      fail-fast: true
      max-parallel: 1 # Prevent race-conditions when creating the base branch, e.g. `version/2026.2`
      matrix:
        tag: ${{ fromJSON(needs.check-tags.outputs.tags) }}
    secrets:
      PAT: ${{ secrets.PAT }}
    uses: ./.github/workflows/generate-openapi-client-on-release.yaml
    with:
      tag-name: ${{ matrix.tag }}
